global using System;
global using System.Data;
global using System.Collections.Generic;
global using System.Linq;
global using Oracle.ManagedDataAccess.Client;
global using Restaurant_Management.Interface;
global using Restaurant_Management.Repository;
global using Restaurant_Management.Model;
global using Oracle.ManagedDataAccess.Types;